# mika.nokka1@gmail.com 8.10.2020 Hämeenlinna
# Starting:  sudo docker-compose -f whoami_https_password.yml up

#
# Does HTTPS connection OK with Lets Encrypt
#

# http://localhost:8088/api/rawdata to see Traefik's API rawdata

# curl -H Host:whoami.docker.localhost http://127.0.0.1 for whoami prompt
# See app.py code for alla available options
#
# Traefik dashboard (if insecure mode on ):
# http://localhost:8088/dashboard/
# Traefik dashboard
# http://traefik.docker.localhost/dashboard/
#
# Access whomai via browser: https://sala.docker.localhost, will ask password (see below)


# Generate basic password as MD5
# htpasswd -bn admin cat (used in this example)
# if any $ in generated password hash, use $$ for correct escaping
# useraccount and passoword in .env file approach in use 
# .env ---> AUTH=admin:$apr1$LqFnjZq8$rQqfi6TsedzIyMTIlpuJU/


version: "3.3"

services:

  traefik:
    image: "traefik:v2.10.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mika.nokka1@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

   
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: containous/whoami:v1.3.0
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`sala.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH}" 
      #- "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$9I5p.8lt$$6gZupKFModminVk.W6FgR/"
    