# https://doc.traefik.io/traefik/getting-started/quick-start/
# mika.nokka1@gmail.com 8.10.2020 Hämeenlinna
#
# TBD
# make -> crete needed volumes and networks, start services
#
# 
# (Volumes host directories must be created first , definitions in .env file
# ./acme.json must be created first + chmod 600 rights set  )
# 
# Collabora (office) has been commented out, works and installs but cant load documents in Nextclod
# (known issue)


version: '3'

networks:
   nextweb: 
     external: false
   extweb:
    external: true
    


services:


  reverse-proxy:
    # The official v2 Traefik docker image
    image: "traefik:v2.10.3"
    # Enables the web UI and tells Traefik to listen to docker
    # unsecure mode for dev in use
    command:
      # not in prod, dashboard
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--api=true"
      - "--certificatesresolvers.letsencrypt.acme.httpChallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=mika.nokka1@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      
    ports:
      - "80:80"
      - "443:443"
      #not in prod:
      #- "8080:8080" 
      #- "192.168.0.32:8081:80"

    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${FILE_ACMEFILE}:/letsencrypt/acme.json"

    labels:
      
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      
      - "traefik.http.routers.reverse-proxy.tls=true"
      - "traefik.http.routers.reverse-proxy-https.tls.certresolver=letsencrypt"

      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      #- traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https
      - "traefik.http.routers.reverse-proxy.rule=Host(`traefik.docker.local`)"

      - traefik.http.routers.reverse-proxy.entrypoints=https
  # - traefik.http.routers.reverse-proxy.middlewares=auth


      # Uncomment to fetch Let's Encrypt certificates.
      # Make sure you set up DNS records and they point to your IP.
      
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https

    networks:
      - nextweb
      - extweb
 
  redis:
    image: redis:latest
    volumes:
      - ${DIR_REDIS}:/data
    ports:
      - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      - nextweb

  # db is nextcloud first screen db name (offers localhost)
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${DIR_DB}:/var/lib/mysql
   
    #usernames and passwors to be used in nextcloud first installation screen
    #see .db_pwds
    env_file:
      .db_pwds
    networks:
      - nextweb
      - extweb

  nextcloud:
    image: nextcloud:27.1.2
    ports:
      - 9090:80
    depends_on:
      - db
      - redis
      - reverse-proxy
    links:
      - db
    environment:
      - REDIS_HOST=redis
    volumes:
      #/var/www/html/data is nextcloud first screen data area offered in setup
      - ${DIR_NEXTCLOUD}:/var/www/html  
    labels: 
      - "traefik.enable=true"
      #one local name (can log in in case ddns is down) , one via dynamic dns (like duckdns.org)
      - "traefik.http.routers.https.rule=Host(`${DDNS_HOST_NAME}`) ||Host(`next.docker.localhost`)"
      - traefik.http.routers.https.entrypoints=websecure
      - traefik.http.routers.https.tls=true
      #- "traefik.http.routers.nextcloud.tls.certresolver=myhttpchallenge"
      #- "traefik.docker.network=extweb"
      - traefik.http.routers.reverse-proxy-https.tls.certresolver=letsencrypt
      #- "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      #- "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$$1/remote.php/dav/"
      #- "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      #- "traefik.http.middlewares.nextcloud-headers.headers.referrerPolicy=no-referrer"
      #- "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=31536000"
      #- "traefik.http.middlewares.nextcloud-headers.headers.forceSTSHeader=true"
      #- "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
      #- "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
      #- "traefik.http.middlewares.nextcloud-headers.headers.browserXssFilter=true"
      #- "traefik.http.middlewares.nextcloud-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      #- "traefik.http.routers.nextcloud-secure.middlewares=nextcloud_redirectregex,nextcloud-headers"
      
    restart: always  
    networks:
      - nextweb
      - extweb

#  collabora:
#    image: collabora/code
#    container_name: collabora
#    restart: unless-stopped
#    networks:
#      - nextweb
#    ports:
#      - 9980:9980
#    expose:
#      - "9980"      
#    environment:
#      #should work as "domain=cloud1\.nextcloud\.com|cloud2\.nextcloud\.com"
#      - "domain=next\\.docker\\.localhost"
#      - aliasgroup1=https://cloud.example.com
#      - "username=admin"
#      - "password=kissa"

#      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"
#    cap_add:
#      - MKNOD
#    volumes:
#      - "./collabora/loolwsd.xml:/etc/loolwsd/loolwsd.xml"
#    tty: true
#    labels:
#      - "traefik.enable=true"
#      - "traefik.docker.network=nextweb"
#      - "traefik.http.routers.collabora.rule=Host(`colla.docker.localhost`)"
#      - "traefik.http.routers.collabora.entrypoints=web"
#      - "traefik.http.middlewares.collabora-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.collabora.middlewares=collabora-https-redirect"
#      - "traefik.http.routers.collabora-secure.entrypoints=websecure"
#      - "traefik.http.routers.collabora-secure.rule=Host(`colla.docker.localhost`)"
#      - "traefik.http.routers.collabora-secure.tls=true"
#      - "traefik.http.routers.collabora-secure.tls.certresolver=letsencrypt" 

